/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = new Collection({
    "createRule": null,
    "deleteRule": null,
    "fields": [
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text3208210256",
        "max": 0,
        "min": 0,
        "name": "id",
        "pattern": "^[a-z0-9]+$",
        "presentable": false,
        "primaryKey": true,
        "required": true,
        "system": true,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "_clone_mxUH",
        "max": 0,
        "min": 0,
        "name": "title",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "help": "",
        "hidden": false,
        "id": "_clone_fD6o",
        "maxSize": 1,
        "name": "description",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "json"
      },
      {
        "help": "",
        "hidden": false,
        "id": "_clone_vNkt",
        "max": null,
        "min": null,
        "name": "position",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "help": "",
        "hidden": false,
        "id": "_clone_7UOU",
        "max": "",
        "min": "",
        "name": "moved_at",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "date"
      },
      {
        "cascadeDelete": false,
        "collectionId": "_pb_users_auth_",
        "help": "",
        "hidden": false,
        "id": "_clone_yS4p",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "created_by",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "relation"
      },
      {
        "cascadeDelete": true,
        "collectionId": "pbc_1809324929",
        "help": "",
        "hidden": false,
        "id": "_clone_kBri",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "section",
        "presentable": false,
        "required": true,
        "system": false,
        "type": "relation"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "_clone_iydJ",
        "max": 0,
        "min": 0,
        "name": "section_name",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "_clone_Ovzd",
        "max": 0,
        "min": 0,
        "name": "section_color",
        "pattern": "^#[A-Fa-f0-9]{6}$",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "_clone_CHXY",
        "max": 0,
        "min": 0,
        "name": "board_name",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "cascadeDelete": false,
        "collectionId": "pbc_2817666393",
        "help": "",
        "hidden": false,
        "id": "_clone_AZJQ",
        "maxSelect": 10,
        "minSelect": 0,
        "name": "subprojects",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "relation"
      },
      {
        "cascadeDelete": true,
        "collectionId": "pbc_3304927325",
        "help": "",
        "hidden": false,
        "id": "_clone_NXji",
        "maxSelect": 0,
        "minSelect": 0,
        "name": "board",
        "presentable": false,
        "required": true,
        "system": false,
        "type": "relation"
      },
      {
        "help": "",
        "hidden": false,
        "id": "_clone_2QjW",
        "maxSelect": 1,
        "name": "priority",
        "presentable": false,
        "required": true,
        "system": false,
        "type": "select",
        "values": [
          "low",
          "medium",
          "high",
          "critical"
        ]
      },
      {
        "help": "",
        "hidden": false,
        "id": "_clone_adQf",
        "max": "",
        "min": "",
        "name": "due_by",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "date"
      },
      {
        "help": "Expected task duration in days. I considered making this a JSON field for future possibilities, but... eh",
        "hidden": false,
        "id": "_clone_aMiI",
        "max": null,
        "min": null,
        "name": "duration_days",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "cascadeDelete": false,
        "collectionId": "pbc_3481593366",
        "help": "Other cards/tasks this one depends on to be started.",
        "hidden": false,
        "id": "_clone_4I4n",
        "maxSelect": 50,
        "minSelect": 0,
        "name": "dependencies",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "relation"
      },
      {
        "help": "",
        "hidden": false,
        "id": "_clone_I4eU",
        "maxSize": 0,
        "name": "assignment_data",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "json"
      },
      {
        "help": "",
        "hidden": false,
        "id": "_clone_9cWl",
        "maxSize": 1,
        "name": "assignment_name_cache",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "json"
      },
      {
        "hidden": false,
        "id": "_clone_Kg6P",
        "name": "created",
        "onCreate": true,
        "onUpdate": false,
        "presentable": false,
        "system": false,
        "type": "autodate"
      },
      {
        "hidden": false,
        "id": "_clone_Lgif",
        "name": "updated",
        "onCreate": true,
        "onUpdate": true,
        "presentable": false,
        "system": false,
        "type": "autodate"
      }
    ],
    "id": "pbc_1503881858",
    "indexes": [],
    "listRule": "@request.auth.id != \"\" &&\n\t(@collection.parts.current_card = id || @collection.parts.past_revision_cards ~ id) &&\n\t@collection.parts.document_id = @request.query.did &&\n\t(@request.query.eid:isset = false || @collection.parts.element_id = @request.query.eid)",
    "name": "part_cards",
    "system": false,
    "type": "view",
    "updateRule": null,
    "viewQuery": "SELECT\n\tid,\n\ttitle, description, position, moved_at, created_by, section, section_name, section_color, board_name, subprojects, board, priority, due_by, duration_days, dependencies, assignment_data, assignment_name_cache, created, updated\nFROM card_preview",
    "viewRule": "@request.auth.id != \"\""
  });

  return app.save(collection);
}, (app) => {
  const collection = app.findCollectionByNameOrId("pbc_1503881858");

  return app.delete(collection);
})
